<?php

/**
* Remote Administration Server Listener
* Listens for connections from remote clients, necessary for initialization or updated settings triggered by a managed server. Only works in conjunction with ProcessAdminRemoteServer.
* You can add custom actions by hooking into AdminRemoteServerListener::moreActions, checking $input->post->arcaction and modifying $origevent.
* ToDo: Use more PW functionality for JSON handling.
* ToDo: Validate client ip against value stored in the client configuration page.
* ToDo: Avoid hooking into ProcessPageView::execute generically. Have ProcessAdminRemoteServer create an endpoint template
*       that we can use with 'autoload' => 'template=endpointtemplate' and set up pages with names unique for every client.
* Development stage: pre-alpha
*
* @author BitPoet
*
* https://github.com/bitpoet/ProcessAdminRemoteServer
* Created 23 January 2016
* 
* ProcessWire 2.x
* Copyright (C) 2011 by Ryan Cramer
* Licensed under GNU/GPL v2, see LICENSE.TXT
*
* http://www.processwire.com
*
*/


class AdminRemoteServerListener extends WireData implements Module {
	public static function getModuleInfo() {
		return array(
			'title'			=>	__('Remote Administration Server Listener', __FILE__),
			'summary'		=>	__('Sets up a listener for connections from the management client', __FILE__),
			'version'		=>	'0.0.7',
			'autoload'		=>	true,
		);
	}

	public function __construct() {
		$this->addHookBefore('ProcessPageView::execute', $this, 'processManagementConnection');
	}
	
	public function processManagementConnection($event) {
		// ToDo: Check client IP
		$post = $this->input->post;
		if( PHP_SAPI == "cli" || $_SERVER["REQUEST_METHOD"] != "POST" || ! $post->arcaction || ! $post->cname || ! $post->srv ) {
			return;
		}
		
		$client = $this->pages->get("ars_serversecret='{$post->srv}'");
		if( $client instanceof NullPage || $client->ars_clientname != $post->cname ) {
			header("Content-Type: application/json"); 
			$event->return = json_encode(array("success" => false, "message" => $this->_("Unknown client")));
			$event->replace = true;
			return $event;
		}
		
		if( $post->arcaction == "initclient" ) {
			if( $client->ars_clientsecret ) {
				header("Content-Type: application/json");
				$event->return = json_encode(array("success" => false, "message" => $this->_("Client already initialized")));
			} elseif( $this->initClientAction($event, $client) !== true ) {
				return $event;
			}
			
		} else if( $post->arcaction == "ping" ) {
			/* Everything okay, ping time is updated at the end of this method */
		} else if( $this->moreActions($event, $client) == false ) {
			header("Content-Type: application/json"); 
			$event->return = json_encode(array("success" => false, "message" => $this->_("Unknown action")));
			$event->replace = true;
			return $event;
			
		}
		
		$client->of(false);
		$client->ars_lastping = strftime("%Y-%m-%d %H:%M:%S");
		$client->save();
		$client->of(true);
		
		header("Content-Type: application/json"); 
		$event->return = json_encode(array("success" => true, "cli" => $client->ars_clientsecret));
		$event->replace = true;
	}
	
	public function ___initClientAction($origevent, $client) {
		$post = $this->input->post;
		
		if( ! $post->cli ) {
			$origevent->return = json_encode(array("success" => false, "message" => $this->_("Missing client identifier")));
			$origevent->replace = true;
			return $origevent;
		}
		
		$client->of(false);
		$client->ars_clientsecret = $post->cli;
		$client->ars_clienturl = $post->url;
		$client->save();
		$client->of(true);
		return true;
	}
	
	/**
	 * Add your own custom actions with this hook.
	 *
	 * To add your own actions here, hook into AdminRemoteServerListener::moreActions.
	 *
	 * To generate your own output, fetch the original event with
	 * `$origevent = $event->arguments(0);`
	 * Get the client information with
	 * `$client = $event->arguments(1);`
	 *
	 * Process $input->post however you like, then replace the original event's output
	 * ```$origevent->return = $your_custom_output;
	 * $origevent->replace = true;```
	 *
	 * Finally, return a true status.
	 * `return true;`
	 */
	public function ___moreActions($origevent, $client) {
		return false;
	}
}
